"""NERDC-aligned subject catalogue used for new and existing schools."""

PRIMARY_SUBJECTS = [
    ("Literacy / Letter Work", "Literacy", "Early Years"),
    ("Numeracy / Number Work", "Numeracy", "Early Years"),
    ("Health Habits / Personal Hygiene", "Health Habits", "Early Years"),
    ("Social Habits", "Social Habits", "Early Years"),
    ("Civic Education", "Civic Education", "Early Years"),
    ("Pre-Science / Basic Science", "Pre-Science", "Early Years"),
    ("Physical and Health Education", "PHE", "Early Years"),
    ("Creativity / Cultural & Creative Arts", "CCA", "Early Years"),
    ("Songs and Rhymes", "Songs", "Early Years"),
    ("Handwriting & Motor Skills Development", "Handwriting", "Early Years"),
    ("English Studies", "English", "Basic 1-6"),
    ("Mathematics", "Mathematics", "Basic 1-6"),
    ("Nigerian Languages (Hausa, Igbo, Yoruba)", "Nigerian Languages", "Basic 1-6"),
    ("Basic Science and Technology", "BST", "Basic 1-6"),
    ("Physical and Health Education", "PHE-PRIMARY", "Basic 1-6"),
    ("Basic Digital Literacy / Computer Studies", "Computer-Primary", "Basic 1-6"),
    ("Christian Religious Studies", "CRS", "Basic 1-6"),
    ("Islamic Studies", "IRS", "Basic 1-6"),
    ("Social and Citizenship Studies / Civic Education", "Civic-Primary", "Basic 1-6"),
    ("Nigerian History", "History-Primary", "Basic 1-6"),
    ("Cultural and Creative Arts (CCA)", "CCA-Primary", "Basic 1-6"),
    ("Pre-Vocational Studies (Agriculture, Home Economics)", "PVS-Primary", "Basic 1-6"),
    ("Verbal Reasoning", "Verbal Reasoning", "Basic 1-6"),
    ("Quantitative Reasoning", "Quantitative Reasoning", "Basic 1-6"),
    ("French", "French", "Basic 1-6"),
    ("Arabic", "Arabic", "Basic 1-6"),
]

SECONDARY_SUBJECTS = [
    ("English Studies", "English-Secondary", "JSS 1-3"),
    ("Mathematics", "Mathematics-Secondary", "JSS 1-3"),
    ("Nigerian Languages (Hausa, Igbo, Yoruba)", "Nigerian-Languages-Secondary", "JSS 1-3"),
    ("Basic Science / Intermediate Science", "Basic Science", "JSS 1-3"),
    ("Basic Technology", "Basic Technology", "JSS 1-3"),
    ("Digital Technologies / Computer Studies", "Computer-Secondary", "JSS 1-3"),
    ("Physical and Health Education", "PHE-Secondary", "JSS 1-3"),
    ("Christian Religious Studies", "CRS-Secondary", "JSS 1-3"),
    ("Islamic Studies", "IRS-Secondary", "JSS 1-3"),
    ("Social and Citizenship Studies / Civic Education", "Civic-Secondary", "JSS 1-3"),
    ("Nigerian History", "History-Secondary", "JSS 1-3"),
    ("Cultural and Creative Arts (CCA)", "CCA-Secondary", "JSS 1-3"),
    ("Business Studies", "Business Studies", "JSS 1-3"),
    ("Pre-Vocational Studies (Agriculture, Home Economics)", "PVS-Secondary", "JSS 1-3"),
    ("French", "French-Secondary", "JSS 1-3"),
    ("Arabic", "Arabic-Secondary", "JSS 1-3"),
    ("English Language", "English Language", "SSS 1-3"),
    ("General Mathematics", "General Mathematics", "SSS 1-3"),
    ("Civic Education / Citizenship and Heritage Studies", "Civic-SSS", "SSS 1-3"),
    ("Digital Technologies / Computer Studies", "Computer-SSS", "SSS 1-3"),
    ("Biology", "Biology", "SSS 1-3"),
    ("Chemistry", "Chemistry", "SSS 1-3"),
    ("Physics", "Physics", "SSS 1-3"),
    ("Further Mathematics", "Further Mathematics", "SSS 1-3"),
    ("Agricultural Science", "Agricultural Science", "SSS 1-3"),
    ("Health Education / Health Science", "Health Education", "SSS 1-3"),
    ("Physical Education", "Physical Education", "SSS 1-3"),
    ("Economics", "Economics", "SSS 1-3"),
    ("Geography", "Geography", "SSS 1-3"),
    ("Government", "Government", "SSS 1-3"),
    ("Literature in English", "Literature", "SSS 1-3"),
    ("History / Nigerian History", "History-SSS", "SSS 1-3"),
    ("Christian Religious Studies", "CRS-SSS", "SSS 1-3"),
    ("Islamic Studies", "IRS-SSS", "SSS 1-3"),
    ("One Nigerian Language (Hausa, Igbo, Yoruba)", "Nigerian Language-SSS", "SSS 1-3"),
    ("French", "French-SSS", "SSS 1-3"),
    ("Arabic", "Arabic-SSS", "SSS 1-3"),
    ("Music", "Music", "SSS 1-3"),
    ("Visual Arts", "Visual Arts", "SSS 1-3"),
    ("Financial Accounting", "Financial Accounting", "SSS 1-3"),
    ("Commerce", "Commerce", "SSS 1-3"),
    ("Office Practice", "Office Practice", "SSS 1-3"),
    ("Insurance", "Insurance", "SSS 1-3"),
    ("Store Management", "Store Management", "SSS 1-3"),
    ("Technical Drawing", "Technical Drawing", "SSS 1-3"),
    ("Auto Mechanics", "Auto Mechanics", "SSS 1-3"),
    ("Applied Electricity", "Applied Electricity", "SSS 1-3"),
    ("Electronics", "Electronics", "SSS 1-3"),
    ("Building Construction", "Building Construction", "SSS 1-3"),
    ("Woodwork", "Woodwork", "SSS 1-3"),
    ("Metalwork", "Metalwork", "SSS 1-3"),
    ("Home Management", "Home Management", "SSS 1-3"),
    ("Foods and Nutrition", "Foods and Nutrition", "SSS 1-3"),
    ("Clothing and Textiles", "Clothing and Textiles", "SSS 1-3"),
    ("Solar Photovoltaic Installation and Maintenance", "Solar PV", "SSS 1-3"),
    ("Fashion Design and Garment Making", "Fashion Design", "SSS 1-3"),
    ("Livestock Farming", "Livestock Farming", "SSS 1-3"),
    ("Beauty and Cosmetology / Hair Styling", "Beauty and Cosmetology", "SSS 1-3"),
    ("Computer Hardware and GSM Repairs", "Computer Hardware", "SSS 1-3"),
    ("Horticulture and Crop Production", "Horticulture", "SSS 1-3"),
    ("Catering Craft Practice", "Catering", "SSS 1-3"),
    ("Auto Body Repair and Spray Painting", "Auto Body Repair", "SSS 1-3"),
    ("Welding and Fabrication Engineering Craft Practice", "Welding", "SSS 1-3"),
    ("Blocklaying, Bricklaying and Concrete Work", "Blocklaying", "SSS 1-3"),
    ("Painting and Decorating", "Painting", "SSS 1-3"),
    ("Plumbing and Pipe Fitting", "Plumbing", "SSS 1-3"),
    ("Machine Woodworking", "Machine Woodworking", "SSS 1-3"),
    ("Carpentry and Joinery", "Carpentry", "SSS 1-3"),
    ("Electrical Installation and Maintenance Work", "Electrical Installation", "SSS 1-3"),
    ("Radio, TV and Electronic Servicing", "Radio TV Servicing", "SSS 1-3"),
    ("Auto Electrical Work", "Auto Electrical", "SSS 1-3"),
    ("Auto Mechanical Work", "Auto Mechanical", "SSS 1-3"),
    ("Air Conditioning and Refrigeration", "AC Refrigeration", "SSS 1-3"),
    ("Animal Husbandry", "Animal Husbandry", "SSS 1-3"),
    ("Fishery", "Fishery", "SSS 1-3"),
    ("Leather Goods Manufacture", "Leather Goods", "SSS 1-3"),
    ("Printing Craft Practice", "Printing", "SSS 1-3"),
    ("Photography", "Photography", "SSS 1-3"),
    ("Tourism", "Tourism", "SSS 1-3"),
    ("Mining", "Mining", "SSS 1-3"),
    ("Marketing", "Marketing", "SSS 1-3"),
    ("Salesmanship", "Salesmanship", "SSS 1-3"),
    ("Stenography", "Stenography", "SSS 1-3"),
    ("Data Processing", "Data Processing", "SSS 1-3"),
]


def seed_subjects(db, school):
    """Insert missing catalogue entries without changing school custom subjects."""
    from . import models as m
    from sqlalchemy import select

    levels = {"PRIMARY": PRIMARY_SUBJECTS, "SECONDARY": SECONDARY_SUBJECTS, "COMBINED": PRIMARY_SUBJECTS + SECONDARY_SUBJECTS}
    existing = set(db.scalars(select(m.Subject.code).where(m.Subject.school_id == school.id)))
    for name, code, category in levels.get(school.school_type, []):
        if code not in existing:
            db.add(m.Subject(school_id=school.id, name=name, code=code, category=category, school_level="PRIMARY" if (name, code, category) in PRIMARY_SUBJECTS else "SECONDARY"))
