"""initial_schema"""

from alembic import op
import sqlalchemy as sa

revision = "a3a12ba1111f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "schools",
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("website", sa.String(length=300), nullable=False),
        sa.Column("registration_number", sa.String(length=80), nullable=False),
        sa.Column("school_type", sa.String(length=20), nullable=False),
        sa.Column("primary_color", sa.String(length=7), nullable=False),
        sa.Column("logo_key", sa.String(length=500), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "academic_sessions",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id", name="uq_academic_sessions_tenant_id"),
        sa.UniqueConstraint("school_id", "name"),
    )
    op.create_index(op.f("ix_academic_sessions_school_id"), "academic_sessions", ["school_id"], unique=False)
    op.create_table(
        "assessment_components",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("weight", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("max_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("weight > 0 AND weight <= 100 AND max_score > 0"),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id", name="uq_assessment_components_tenant_id"),
        sa.UniqueConstraint("school_id", "name"),
    )
    op.create_index(op.f("ix_assessment_components_school_id"), "assessment_components", ["school_id"], unique=False)
    op.create_table(
        "class_levels",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id", name="uq_class_levels_tenant_id"),
        sa.UniqueConstraint("school_id", "name"),
    )
    op.create_index(op.f("ix_class_levels_school_id"), "class_levels", ["school_id"], unique=False)
    op.create_table(
        "grading_scales",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id"),
    )
    op.create_index(op.f("ix_grading_scales_school_id"), "grading_scales", ["school_id"], unique=False)
    op.create_table(
        "notification_templates",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("event", sa.String(length=50), nullable=False),
        sa.Column("channel", sa.String(length=10), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "event", "channel"),
        sa.UniqueConstraint("school_id", "id", name="uq_notification_templates_tenant_id"),
    )
    op.create_index(op.f("ix_notification_templates_school_id"), "notification_templates", ["school_id"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("permission_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "subjects",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("compulsory", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "code"),
        sa.UniqueConstraint("school_id", "id", name="uq_subjects_tenant_id"),
    )
    op.create_index(op.f("ix_subjects_school_id"), "subjects", ["school_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("password_hash", sa.String(length=300), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("school_id", "id"),
    )
    op.create_index(op.f("ix_users_school_id"), "users", ["school_id"], unique=False)
    op.create_table(
        "announcements",
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "created_by"], ["users.school_id", "users.id"], name="fk_announcements_created_by_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id"),
    )
    op.create_index(op.f("ix_announcements_school_id"), "announcements", ["school_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "actor_id"], ["users.school_id", "users.id"], name="fk_audit_logs_actor_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id"),
    )
    op.create_index(op.f("ix_audit_logs_school_id"), "audit_logs", ["school_id"], unique=False)
    op.create_table(
        "auth_tokens",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id", "user_id"], ["users.school_id", "users.id"], name="fk_auth_tokens_user_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_auth_tokens_school_id"), "auth_tokens", ["school_id"], unique=False)
    op.create_index(op.f("ix_auth_tokens_user_id"), "auth_tokens", ["user_id"], unique=False)
    op.create_table(
        "class_arms",
        sa.Column("level_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("teacher_id", sa.String(length=36), nullable=True),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["class_levels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "level_id"],
            ["class_levels.school_id", "class_levels.id"],
            name="fk_class_arms_level_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "teacher_id"], ["users.school_id", "users.id"], name="fk_class_arms_teacher_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id", name="uq_class_arms_tenant_id"),
        sa.UniqueConstraint("school_id", "level_id", "name"),
    )
    op.create_index(op.f("ix_class_arms_school_id"), "class_arms", ["school_id"], unique=False)
    op.create_table(
        "grading_scale_items",
        sa.Column("scale_id", sa.String(length=36), nullable=False),
        sa.Column("label", sa.String(length=20), nullable=False),
        sa.Column("min_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("max_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("remark", sa.String(length=180), nullable=False),
        sa.Column("passing", sa.Boolean(), nullable=False),
        sa.Column("point_value", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("min_score >= 0 AND max_score <= 100 AND min_score <= max_score"),
        sa.ForeignKeyConstraint(
            ["scale_id"],
            ["grading_scales.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "scale_id"],
            ["grading_scales.school_id", "grading_scales.id"],
            name="fk_grading_scale_items_scale_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id", name="uq_grading_scale_items_tenant_id"),
    )
    op.create_index(op.f("ix_grading_scale_items_school_id"), "grading_scale_items", ["school_id"], unique=False)
    op.create_table(
        "parents",
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("notify_email", sa.Boolean(), nullable=False),
        sa.Column("notify_sms", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id", "user_id"], ["users.school_id", "users.id"], name="fk_parents_user_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_parents_school_id"), "parents", ["school_id"], unique=False)
    op.create_table(
        "staff",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=False),
        sa.Column("job_title", sa.String(length=100), nullable=False),
        sa.Column("employment_date", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id", "user_id"], ["users.school_id", "users.id"], name="fk_staff_user_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_staff_school_id"), "staff", ["school_id"], unique=False)
    op.create_table(
        "terms",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id", "session_id"],
            ["academic_sessions.school_id", "academic_sessions.id"],
            name="fk_terms_session_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["academic_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id", name="uq_terms_tenant_id"),
        sa.UniqueConstraint("session_id", "name"),
    )
    op.create_index(op.f("ix_terms_school_id"), "terms", ["school_id"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "user_id"], ["users.school_id", "users.id"], name="fk_user_roles_user_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id", name="uq_user_roles_tenant_id"),
        sa.UniqueConstraint("user_id", "role_id"),
    )
    op.create_index(op.f("ix_user_roles_school_id"), "user_roles", ["school_id"], unique=False)
    op.create_table(
        "fee_structures",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("term_id", sa.String(length=36), nullable=False),
        sa.Column("class_id", sa.String(length=36), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class_arms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "class_id"],
            ["class_arms.school_id", "class_arms.id"],
            name="fk_fee_structures_class_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "term_id"], ["terms.school_id", "terms.id"], name="fk_fee_structures_term_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id"),
    )
    op.create_index(op.f("ix_fee_structures_school_id"), "fee_structures", ["school_id"], unique=False)
    op.create_table(
        "students",
        sa.Column("student_code", sa.String(length=60), nullable=False),
        sa.Column("admission_no", sa.String(length=80), nullable=True),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("middle_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(length=30), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("emergency_info", sa.Text(), nullable=False),
        sa.Column("admission_date", sa.Date(), nullable=True),
        sa.Column("class_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("photo_key", sa.String(length=500), nullable=True),
        sa.Column("qr_version", sa.Integer(), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('ACTIVE','INACTIVE','WITHDRAWN','GRADUATED','TRANSFERRED')"),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class_arms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "class_id"], ["class_arms.school_id", "class_arms.id"], name="fk_students_class_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "admission_no"),
        sa.UniqueConstraint("school_id", "id", name="uq_students_tenant_id"),
        sa.UniqueConstraint("school_id", "student_code"),
    )
    op.create_index(op.f("ix_students_class_id"), "students", ["class_id"], unique=False)
    op.create_index(op.f("ix_students_school_id"), "students", ["school_id"], unique=False)
    op.create_table(
        "subject_assignments",
        sa.Column("class_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("teacher_id", sa.String(length=36), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class_arms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "class_id"],
            ["class_arms.school_id", "class_arms.id"],
            name="fk_subject_assignments_class_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "subject_id"],
            ["subjects.school_id", "subjects.id"],
            name="fk_subject_assignments_subject_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "teacher_id"],
            ["users.school_id", "users.id"],
            name="fk_subject_assignments_teacher_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "class_id", "subject_id"),
        sa.UniqueConstraint("school_id", "id", name="uq_subject_assignments_tenant_id"),
    )
    op.create_index(op.f("ix_subject_assignments_school_id"), "subject_assignments", ["school_id"], unique=False)
    op.create_table(
        "timetable_entries",
        sa.Column("class_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("teacher_id", sa.String(length=36), nullable=False),
        sa.Column("room", sa.String(length=80), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("start_time < end_time"),
        sa.CheckConstraint("weekday >= 0 AND weekday <= 6"),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class_arms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "class_id"],
            ["class_arms.school_id", "class_arms.id"],
            name="fk_timetable_entries_class_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "subject_id"],
            ["subjects.school_id", "subjects.id"],
            name="fk_timetable_entries_subject_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "teacher_id"], ["users.school_id", "users.id"], name="fk_timetable_entries_teacher_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id", name="uq_timetable_entries_tenant_id"),
    )
    op.create_index(op.f("ix_timetable_entries_school_id"), "timetable_entries", ["school_id"], unique=False)
    op.create_table(
        "attendance",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("class_id", sa.String(length=36), nullable=False),
        sa.Column("term_id", sa.String(length=36), nullable=False),
        sa.Column("attendance_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("marked_by", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('PRESENT','ABSENT','LATE','EXCUSED')"),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class_arms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["marked_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "class_id"], ["class_arms.school_id", "class_arms.id"], name="fk_attendance_class_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "marked_by"], ["users.school_id", "users.id"], name="fk_attendance_marked_by_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "student_id"], ["students.school_id", "students.id"], name="fk_attendance_student_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "term_id"], ["terms.school_id", "terms.id"], name="fk_attendance_term_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id", name="uq_attendance_tenant_id"),
        sa.UniqueConstraint("student_id", "attendance_date", "term_id"),
    )
    op.create_index(op.f("ix_attendance_attendance_date"), "attendance", ["attendance_date"], unique=False)
    op.create_index(op.f("ix_attendance_school_id"), "attendance", ["school_id"], unique=False)
    op.create_index(op.f("ix_attendance_student_id"), "attendance", ["student_id"], unique=False)
    op.create_table(
        "fee_items",
        sa.Column("structure_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0"),
        sa.ForeignKeyConstraint(
            ["school_id", "structure_id"],
            ["fee_structures.school_id", "fee_structures.id"],
            name="fk_fee_items_structure_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["structure_id"],
            ["fee_structures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id", name="uq_fee_items_tenant_id"),
        sa.UniqueConstraint("structure_id", "name"),
    )
    op.create_index(op.f("ix_fee_items_school_id"), "fee_items", ["school_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("term_id", sa.String(length=36), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("method", sa.String(length=40), nullable=False),
        sa.Column("reference", sa.String(length=120), nullable=False),
        sa.Column("receipt_number", sa.String(length=80), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("recorded_by", sa.String(length=36), nullable=False),
        sa.Column("previous_balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("new_balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("reversed", sa.Boolean(), nullable=False),
        sa.Column("reversal_reason", sa.Text(), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0"),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "recorded_by"], ["users.school_id", "users.id"], name="fk_payments_recorded_by_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "student_id"], ["students.school_id", "students.id"], name="fk_payments_student_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "term_id"], ["terms.school_id", "terms.id"], name="fk_payments_term_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id", name="uq_payments_tenant_id"),
        sa.UniqueConstraint("school_id", "idempotency_key"),
        sa.UniqueConstraint("school_id", "receipt_number"),
    )
    op.create_index(op.f("ix_payments_school_id"), "payments", ["school_id"], unique=False)
    op.create_index(op.f("ix_payments_student_id"), "payments", ["student_id"], unique=False)
    op.create_table(
        "results",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("class_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("term_id", sa.String(length=36), nullable=False),
        sa.Column("total", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("grade", sa.String(length=20), nullable=False),
        sa.Column("remark", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("entered_by", sa.String(length=36), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('DRAFT','SUBMITTED','APPROVED','PUBLISHED')"),
        sa.CheckConstraint("total >= 0 AND total <= 100"),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class_arms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entered_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "class_id"], ["class_arms.school_id", "class_arms.id"], name="fk_results_class_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "entered_by"], ["users.school_id", "users.id"], name="fk_results_entered_by_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "student_id"], ["students.school_id", "students.id"], name="fk_results_student_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "subject_id"], ["subjects.school_id", "subjects.id"], name="fk_results_subject_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "term_id"], ["terms.school_id", "terms.id"], name="fk_results_term_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id", name="uq_results_tenant_id"),
        sa.UniqueConstraint("student_id", "subject_id", "term_id"),
    )
    op.create_index(op.f("ix_results_school_id"), "results", ["school_id"], unique=False)
    op.create_index(op.f("ix_results_student_id"), "results", ["student_id"], unique=False)
    op.create_table(
        "student_parents",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=False),
        sa.Column("relationship", sa.String(length=50), nullable=False),
        sa.Column("primary_contact", sa.Boolean(), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["parents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "parent_id"], ["parents.school_id", "parents.id"], name="fk_student_parents_parent_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "student_id"],
            ["students.school_id", "students.id"],
            name="fk_student_parents_student_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id", name="uq_student_parents_tenant_id"),
        sa.UniqueConstraint("student_id", "parent_id"),
    )
    op.create_index(op.f("ix_student_parents_school_id"), "student_parents", ["school_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("term_id", sa.String(length=36), nullable=False),
        sa.Column("payment_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("format", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("email_parents", sa.Boolean(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(), nullable=False),
        sa.Column("last_error", sa.String(length=300), nullable=True),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "payment_id"], ["payments.school_id", "payments.id"], name="fk_documents_payment_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "student_id"], ["students.school_id", "students.id"], name="fk_documents_student_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "term_id"], ["terms.school_id", "terms.id"], name="fk_documents_term_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id"),
    )
    op.create_index(op.f("ix_documents_school_id"), "documents", ["school_id"], unique=False)
    op.create_index(op.f("ix_documents_status"), "documents", ["status"], unique=False)
    op.create_table(
        "result_scores",
        sa.Column("result_id", sa.String(length=36), nullable=False),
        sa.Column("component_id", sa.String(length=36), nullable=False),
        sa.Column("score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("max_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("weight", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("score >= 0 AND score <= max_score"),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["assessment_components.id"],
        ),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "component_id"],
            ["assessment_components.school_id", "assessment_components.id"],
            name="fk_result_scores_component_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "result_id"], ["results.school_id", "results.id"], name="fk_result_scores_result_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("result_id", "component_id"),
        sa.UniqueConstraint("school_id", "id", name="uq_result_scores_tenant_id"),
    )
    op.create_index(op.f("ix_result_scores_school_id"), "result_scores", ["school_id"], unique=False)
    op.create_table(
        "student_charges",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("term_id", sa.String(length=36), nullable=False),
        sa.Column("fee_item_id", sa.String(length=36), nullable=True),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0 AND discount >= 0 AND discount <= amount"),
        sa.ForeignKeyConstraint(
            ["fee_item_id"],
            ["fee_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "fee_item_id"],
            ["fee_items.school_id", "fee_items.id"],
            name="fk_student_charges_fee_item_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "student_id"],
            ["students.school_id", "students.id"],
            name="fk_student_charges_student_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "term_id"], ["terms.school_id", "terms.id"], name="fk_student_charges_term_id_tenant"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("school_id", "id", name="uq_student_charges_tenant_id"),
        sa.UniqueConstraint("student_id", "term_id", "fee_item_id"),
    )
    op.create_index(op.f("ix_student_charges_school_id"), "student_charges", ["school_id"], unique=False)
    op.create_index(op.f("ix_student_charges_student_id"), "student_charges", ["student_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("channel", sa.String(length=10), nullable=False),
        sa.Column("recipient", sa.String(length=254), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("event_key", sa.String(length=250), nullable=False),
        sa.Column("provider_id", sa.String(length=200), nullable=True),
        sa.Column("document_id", sa.String(length=36), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(), nullable=False),
        sa.Column("last_error", sa.String(length=300), nullable=True),
        sa.Column("school_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id", "document_id"],
            ["documents.school_id", "documents.id"],
            name="fk_notifications_document_id_tenant",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_key"),
        sa.UniqueConstraint("school_id", "id"),
    )
    op.create_index(op.f("ix_notifications_school_id"), "notifications", ["school_id"], unique=False)
    op.create_index(op.f("ix_notifications_status"), "notifications", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notifications_status"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_school_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_student_charges_student_id"), table_name="student_charges")
    op.drop_index(op.f("ix_student_charges_school_id"), table_name="student_charges")
    op.drop_table("student_charges")
    op.drop_index(op.f("ix_result_scores_school_id"), table_name="result_scores")
    op.drop_table("result_scores")
    op.drop_index(op.f("ix_documents_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_school_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_student_parents_school_id"), table_name="student_parents")
    op.drop_table("student_parents")
    op.drop_index(op.f("ix_results_student_id"), table_name="results")
    op.drop_index(op.f("ix_results_school_id"), table_name="results")
    op.drop_table("results")
    op.drop_index(op.f("ix_payments_student_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_school_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_fee_items_school_id"), table_name="fee_items")
    op.drop_table("fee_items")
    op.drop_index(op.f("ix_attendance_student_id"), table_name="attendance")
    op.drop_index(op.f("ix_attendance_school_id"), table_name="attendance")
    op.drop_index(op.f("ix_attendance_attendance_date"), table_name="attendance")
    op.drop_table("attendance")
    op.drop_index(op.f("ix_timetable_entries_school_id"), table_name="timetable_entries")
    op.drop_table("timetable_entries")
    op.drop_index(op.f("ix_subject_assignments_school_id"), table_name="subject_assignments")
    op.drop_table("subject_assignments")
    op.drop_index(op.f("ix_students_school_id"), table_name="students")
    op.drop_index(op.f("ix_students_class_id"), table_name="students")
    op.drop_table("students")
    op.drop_index(op.f("ix_fee_structures_school_id"), table_name="fee_structures")
    op.drop_table("fee_structures")
    op.drop_index(op.f("ix_user_roles_school_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_terms_school_id"), table_name="terms")
    op.drop_table("terms")
    op.drop_index(op.f("ix_staff_school_id"), table_name="staff")
    op.drop_table("staff")
    op.drop_index(op.f("ix_parents_school_id"), table_name="parents")
    op.drop_table("parents")
    op.drop_index(op.f("ix_grading_scale_items_school_id"), table_name="grading_scale_items")
    op.drop_table("grading_scale_items")
    op.drop_index(op.f("ix_class_arms_school_id"), table_name="class_arms")
    op.drop_table("class_arms")
    op.drop_index(op.f("ix_auth_tokens_user_id"), table_name="auth_tokens")
    op.drop_index(op.f("ix_auth_tokens_school_id"), table_name="auth_tokens")
    op.drop_table("auth_tokens")
    op.drop_index(op.f("ix_audit_logs_school_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_announcements_school_id"), table_name="announcements")
    op.drop_table("announcements")
    op.drop_index(op.f("ix_users_school_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_subjects_school_id"), table_name="subjects")
    op.drop_table("subjects")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_notification_templates_school_id"), table_name="notification_templates")
    op.drop_table("notification_templates")
    op.drop_index(op.f("ix_grading_scales_school_id"), table_name="grading_scales")
    op.drop_table("grading_scales")
    op.drop_index(op.f("ix_class_levels_school_id"), table_name="class_levels")
    op.drop_table("class_levels")
    op.drop_index(op.f("ix_assessment_components_school_id"), table_name="assessment_components")
    op.drop_table("assessment_components")
    op.drop_index(op.f("ix_academic_sessions_school_id"), table_name="academic_sessions")
    op.drop_table("academic_sessions")
    op.drop_table("schools")
    op.drop_table("roles")
    op.drop_table("permissions")
    # ### end Alembic commands ###
